### ISSUE TITLE
[newa_traditional] not rendering

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keymanweb.com#10]
The newa_traditional keyboard from keymanapp/keyboards#1084
is not rendering on https://keymanweb.com/#new-newa,Keyboard_newa_traditional

![newa](https://user-images.githubusercontent.com/7358010/75848880-0b4b5800-5e16-11ea-9aa5-1574c98ca86b.png)

**Comment by LornaSIL** [comment]
Should Iwe try the ttf instead of the otf?

**Comment by sapradhan** [comment]
I was wrong when I initially report that OSK was not rendering property even when Noto Sans Newa was present locally. This only occurs when it isnt. 

I see that Noto Sans Newa  was pushed to s.keyman.com
do we need to add `@font-face` referencing this somewhere ?

**Comment by sapradhan** [comment]
https://help.keyman.com/keyboard/newa_traditional/1.0/newa_traditional
is also not rendering properly. 
Upon inspecting the DOM, i find that  `font-family` for keycaps computes to `Tahoma, Helvetica`. Firefox and Chrome are still figure out they need to use Noto Sans Newa if its installed locally. Edge however fails to do so. 
If the font is not installed locally, rendering fails results similar to the screenshot above in all browsers.

**Comment by mcdurdin** [comment]
The issue on keymanweb.com is now resolved with https://github.com/keymanapp/keyman/pull/2780 and https://github.com/keymanapp/keyman/pull/2781 and https://github.com/keymanapp/s.keyman.com/pull/17.

Follow https://github.com/keymanapp/help.keyman.com/issues/150 and https://github.com/keymanapp/keyman/issues/2784 for the issue on help.keyman.com.
