### ISSUE TITLE
The download button shown when browsing on Windows doesn't get shown in macOS

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keymanweb.com#53]
Look at the right side of the textbook to see the different between what is shown in Windows and macOS. The download button is not shown in macOS. If this is intended, close this bug.

KeymanWeb.com on Chrome in Windows
<img width="500" alt="image" src="https://user-images.githubusercontent.com/28331388/186067272-48f6fa4f-f1d8-4e43-9801-a6762a572af6.png">

KeymanWeb.com on Chrome in macOS
<img width="500" alt="image" src="https://user-images.githubusercontent.com/28331388/186067092-a58886d5-21ec-460b-a8c0-fe002693249a.png">

**Comment by mcdurdin** [comment]
Yeah, we don't currently have bundled installs for macOS, so it's less valuable there. We'll revisit this one day for mac, but closing for now.
