### ISSUE TITLE
bug: Languages dropdown menu is missing in KeymanWeb 17.0.142 build

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keymanweb.com#77]
Here, What I did is:
1. Opened Keyman 17.0.142 alpha build in any browser. 
2. Clicked the Languages dropdown list. 

Here, I noticed that the language list menu was missing on the screen. 

Note: I am not seeing this issue in Keyman 16.0.139 stable build. 

I have attached the screenshot for reference. 

..Language list menu appears correctly in Keyman 16.0.139

   <img width="300" src="https://github.com/keymanapp/keymanweb.com/assets/19683143/c5955881-bac0-456c-8a98-e6c02cc957c4">

..Languages list menu was missing in Keyman 17.0.142 build

   <img width="300" src="https://github.com/keymanapp/keymanweb.com/assets/19683143/6cb8398f-7c64-4342-abfb-cb7153de9d53">

..Error message appears while opening in Chrome browser

   <img width="300" src="https://github.com/keymanapp/keymanweb.com/assets/19683143/31dd9c92-bf95-4d89-9025-e09af0123ba9">

**Comment by jahorton** [comment]
Confirmed:  keyboards are available as expected with the fix.  (Verified via https://keymanweb.com/?version=17.0.145 now that it's live.)
